---
## Packages installed with services disabled
- name: hapee {{ hapee.version }}{{ hapee.release }} Business Subscription is installed
  yum: name={{ item }} state=installed
  with_items: 
    - hapee-{{ hapee.version }}{{ hapee.release }}-base    
                                      #Common settings required by other components
    - hapee-{{ hapee.version }}{{ hapee.release }}-lb      
                                      #Starter HAProxy Load-balancer
    - hapee-{{ hapee.version }}{{ hapee.release }}-cli     
                                      #Socat Client to connect/interract with running HAProxy instance
    - hapee-{{ hapee.version }}{{ hapee.release }}-vrrp    
                                      #Virtual IP high-availability between nodes of a cluster
    - hapee-{{ hapee.version }}{{ hapee.release }}-cli-lb  
                                      #Scripts to ease control of HAProxy through its socket   
    - hapee-{{ hapee.version }}{{ hapee.release }}-log     
                                      #Autonomous log system based on default operating system syslog daemon
    - hapee-{{ hapee.version }}{{ hapee.release }}-snmp-lb 
                                      #Load-Balancing counters available through SNMP daemon
  tags: ['pkg-main']

- replace: # Bug Fix Service Syntax
          # path: "{{ item.file }}"
          dest: "{{ item.file }}"
          regexp: '{{ item.text1 }}'
          replace: '{{ item.text2 }}'
  when: bug_fix | d('yes') | bool
  with_items:
    - { text1: 'PIDFILE=/run/hapee-1.6-lb.pid', text2: 'PIDFILE=/var/run/hapee-{{ hapee.version }}/hapee-lb.pid', 
        file: '/usr/lib/systemd/system/hapee-1.6-lb.service' }
    - { text1: '@@HAPEE_MAJORVERSION@@', text2: '{{ hapee.version }}', 
        file: '/etc/init.d/hapee-{{ hapee.version }}-log' }
  tags: ['pkg-main']


- name: hapee {{ hapee.version }}{{ hapee.release }} Extension to allow automatic map or acl updates download through HTTP
  when: install_extension | d('no') | bool
  yum: name={{ item }} state=installed
  with_items: 
    - hapee-{{ hapee.version }}{{ hapee.release }}-update
  tags: ['pkg-extension','pkg-acl-update']

- name: hapee {{ hapee.version }}{{ hapee.release }} Extension Advanced Persistent Threat protection
  when: install_extension | d('no') | bool
  yum: name={{ item }} state=installed
  with_items: 
    - hapee-{{ hapee.version }}{{ hapee.release }}-lb-sanitize
  tags: ['pkg-extension','pkg-lb-sanitize']

- name: hapee {{ hapee.version }}{{ hapee.release }} Extension Challenge/response botnet protection module
  when: install_extension | d('no') | bool
  yum: name={{ item }} state=installed
  with_items: 
    - hapee-{{ hapee.version }}{{ hapee.release }}-lb-antibot
  tags: ['pkg-extension','pkg-lb-antibot']

- name: hapee {{ hapee.version }}{{ hapee.release }} Extension Route Health Injection
  when: install_extension | d('no') | bool
  yum: name={{ item }} state=installed
  with_items: 
    - hapee-{{ hapee.version }}{{ hapee.release }}-route
  tags: ['pkg-extension','pkg-bird_rhi']


## Config files instantiated
         
- name: Setup hapee-lb core configuration file
  template: src=hapee-lb.cfg.j2
            dest=/etc/hapee-{{ hapee.version }}/hapee-lb.cfg
            mode=0644
            owner=root
            group=root
  tags: ['base_config','hapee-config_update']  # use tag hapee-config_update for config modify
  notify: Restart hapee-lb service

- name: Setup vrrp configuration files
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            mode="{{ item.mode }}"
            owner=root
            group=root
  with_items:
    - { src: 'hapee-vrrp.cfg.j2', dest: '/etc/hapee-{{ hapee.version }}/hapee-vrrp.cfg', mode: '0644' }
    - { src: 'proc_chk.sh.j2', dest: '/etc/hapee-{{ hapee.version }}/proc_chk.sh', mode: '0755' }
  tags: ['vrrp_config','hapee-config_update']   
  notify: Restart hapee-vrrp service

- name: Instantiate hapee Autonomous log system configuration file
  template: src=hapee-log.cfg.j2
            dest=/etc/hapee-{{ hapee.version }}/hapee-log.cfg
            mode=0644
            owner=root
            group=root
  tags: ['log_config']
  notify: Restart hapee-log service

- name: Instantiate hapee rsyslog configuration file
  template: src=rsyslog-hapee.conf.j2
            dest=/etc/rsyslog.d/hapee.conf
            mode=0644
            owner=root
            group=root
  tags: ['log_config']
  notify: Restart rsyslog service  

- name: Remove default logging directory  
  file:
    path: /var/log/hapee-{{ hapee.version }}
    state: absent
  tags: ['log_config']    

- name: Remove default cert  
  file:
    path: /etc/hapee-{{ hapee.version }}/certs/ssl.pem
    state: absent
  tags: ['base_config']  

- name: Update snmpd config 
  lineinfile:
            dest: /etc/snmp/snmpd.conf
            line: 'pass_persist  .1.3.6.1.4.1.23263.4.3.1.3 /opt/hapee-1.6/bin/hapee-snmp-lb'
            state: present
  notify: Restart snmpd service
  tags: ['snmpd_config']  

- name: Instantiate hapee sysctl configuration file
  template: src=hapee-sysctl.conf.j2
            dest=/etc/sysctl.d/hapee-sysctl.conf
            mode=0644
            owner=root
            group=root
  notify: reload sysctl
  tags: ['sysctl_config']

- name: Instantiate hapee logrotate configuration file
  template: src=hapee.logrotate.j2
            dest=/etc/logrotate.d/hapee
            mode=0644
            owner=root
            group=root
  tags: ['logrotate_config']

- name: Ensure hapee SSL certificate directories are present
  file: path=/etc/hapee-{{ hapee.version }}/certs/{{ item.domain }}
        state=directory
        mode=0755
        owner=root
        group=root
  with_items:
    - "{{ hapee.ssl }}"
  tags: ['ssl_cert_config']

- name: Copy Vault Decrypted hapee SSL certificates
  copy: content={{ item.cert }}
        dest=/etc/hapee-{{ hapee.version }}/certs/{{ item.domain }}/{{ item.domain }}.pem
        mode=0644
        owner=root
        group=root
  with_items:
    - "{{ hapee.ssl }}"
  tags: ['ssl_cert_config']

  
- systemd: name='{{ item.svc }}' daemon_reload=yes enabled=yes masked=no 
  with_items: 
    - svc: 'hapee-{{ hapee.version }}-log'
    - svc: 'hapee-{{ hapee.version }}-lb'
    - svc: 'hapee-{{ hapee.version }}-vrrp'

- meta: flush_handlers

