---
# template.yml PURPOSE
- name: PURPOSE
  debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
  tags:
    - tag_test

- debug:
    msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
  when: ansible_default_ipv4.gateway is defined
  tags: ['pkg-main']
  
- shell: /usr/bin/uptime
  register: result

- debug:
    var: result
    verbosity: 1
  tags: tag_result 


- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
          # A number that controls when the debug is run, 
          # if you set to 3 it will only run debug when -vvv or above
  tags: [tag1,tag2,"{{ hapee.stats.username }}"]
  
# - meta: flush_handlers
